name: CI/CD Supabase Task

# 1. Khi nào thì chạy? (Khi push code lên nhánh main)
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 2. Lấy code từ repo về máy ảo của GitHub
      - uses: actions/checkout@v4

      # 3. Cài đặt môi trường Node.js
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 4. Cài đặt thư viện (npm install)
      - run: npm install

      # 5. Chạy lệnh Build (Ví dụ: npm run build)
      # Tại đây ta truyền Secret vào để lúc Build nó không bị lỗi "undefined"
      - name: Build Project
        env:
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: npm run build
